import { getQueryString } from '@/utils/index'

const features = {
  en: {
    data: [
      {
        id: 1,
        content:
          'The project is developed based on the latest <a target="_blank" href="https://v3.cn.vuejs.org/guide/introduction.html">vue3</a> family bucket, fully using the latest <a target="_blank" href="https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md">RFC script setup</ a>Syntax standards, bring you a different vue3 development experience',
        title: 'Vue3 + family bucket',
        percentage: 100
      },
      {
        id: 2,
        content:
          '<a target="_blank" href="https://element-plus.org/#/zh-CN">Element Plus</a>, a set for developers, designers and product managers The desktop component library based on Vue 3.0. Is the official vue 3 compatible version of Element UI',
        title: 'Element-Plus',
        percentage: 100
      },
      {
        id: 3,
        content:
          '<a target="_blank" href="https://panjiachen.github.io/vue-element-admin-site/zh/guide/">vue-element-admin</a> is a backend Front-end solution, it is based on vue and element-ui implementation, and 70K <a target="_blank" href="https://github.com/PanJiaChen/vue-element-admin">star< /a>. <br />This project uses the latest vue technology to reconstruct it, and expand its existing functions, and is committed to bringing you a front-end technology solution that is more in line with <b>modern back-end development</b >',
        title: 'vue-element-admin',
        percentage: 100
      },
      {
        id: 4,
        content:
          'ESLint corresponds to the coding standard, and Git Hooks corresponds to the Git standard. <br /> If you want to develop a large-scale enterprise-level project, you need to start with the specifications!',
        title: 'ESLint + Git Hooks',
        percentage: 100
      },
      {
        id: 5,
        content:
          "Ali front-end P7 post is called 'technical expert', and some people like to call them 'front-end architect'. Since they are called 'architect', architecture design is of course an indispensable part.",
        title: 'Architecture design',
        percentage: 100
      },
      {
        id: 6,
        content:
          'A comprehensive background authority verification system, which implements a full range of authority functions such as <b>page authority, function authority, dynamic authority, authority configuration</b>, etc.',
        title:
          'Authority verification (page authority, function authority, dynamic authority, authority configuration)',
        percentage: 100
      },
      {
        id: 7,
        content: 'Function guidance to users',
        title: 'Function guide',
        percentage: 100
      },
      {
        id: 8,
        content:
          'Realize the real <b>configuration Menu</b> according to the Menu menu dynamically generated by the routing',
        title: 'Configurable + shrink sidebar',
        percentage: 100
      },
      {
        id: 9,
        content: 'Dynamically generated breadcrumb data',
        title: 'Dynamic breadcrumbs',
        percentage: 100
      },
      {
        id: 10,
        content: 'Notes quick navigation function',
        title: 'Tags View',
        percentage: 100
      },
      {
        id: 11,
        content:
          'Customized svg Icon is automatically assigned and imported with el Icon',
        title: 'svg sprite icon',
        percentage: 100
      },
      {
        id: 12,
        content: 'Multi-language internationalization function realization',
        title: 'Internationalization',
        percentage: 100
      },
      {
        id: 13,
        content: 'Theme replacement function, provide cache implementation',
        title: 'Dynamic skinning',
        percentage: 100
      },
      {
        id: 14,
        content:
          'Search data based on the page automatically generated by the routing configuration, without manual configuration',
        title: 'Page search',
        percentage: 100
      },
      {
        id: 15,
        content: 'Import and export of excel tables',
        title: 'excel export, import',
        percentage: 100
      },
      {
        id: 16,
        content: 'Export page data as zip',
        title: 'zip import',
        percentage: 100
      },
      {
        id: 17,
        content:
          'Commonly used editor functions, including rich text editor && MarkDown editor',
        title: 'Rich text + MarkDown editor',
        percentage: 100
      },
      {
        id: 18,
        content:
          'Common operations of table lists are mostly used in display functions that contain table items. Including: dynamic table && drag and drop table && inline editing table',
        title: 'Dynamic table + drag and drop table + inline editing table',
        percentage: 100
      },
      {
        id: 19,
        content:
          'The page-level error handling is handled uniformly by vue-router. Including 401 and 404 error handling',
        title: 'Unified error handling',
        percentage: 100
      },
      {
        id: 20,
        content: 'Build and release',
        title: 'release',
        percentage: 100
      },
      {
        id: 21,
        content:
          'In addition to the above functions, we have also implemented many other functions, such as: CDN, dynamic environment variable configuration, lazy loading, cross-domain, etc.',
        title: 'other',
        percentage: 100
      }
    ]
  },
  zh: {
    data: [
      {
        id: 1,
        content:
          '项目基于最新的<a target="_blank" href="https://v3.cn.vuejs.org/guide/introduction.html">vue3</a>全家桶进行开发，全面使用最新的的<a target="_blank" href="https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md">RFC script setup</a>语法标准，为你带来不一样的 vue3 开发体验',
        title: 'Vue3 + 全家桶',
        percentage: 100
      },
      {
        id: 2,
        content:
          '<a target="_blank" href="https://element-plus.org/#/zh-CN">Element Plus</a>，一套为开发者、设计师和产品经理准备的基于 Vue 3.0 的桌面端组件库。是 Element UI 的官方 vue 3 兼容版本',
        title: 'Element-Plus',
        percentage: 100
      },
      {
        id: 3,
        content:
          '<a target="_blank" href="https://panjiachen.github.io/vue-element-admin-site/zh/guide/">vue-element-admin</a> 是一个后台前端解决方案，它基于 vue 和 element-ui实现，并有用 70K 的 <a target="_blank" href="https://github.com/PanJiaChen/vue-element-admin">star</a>。<br />本项目使用最新 vue 技术对其进行了重构，并在其现有功能上进行了扩展，致力于为大家带来更加符合 <b>现代后台开发的前端技术解决方案</b>',
        title: 'vue-element-admin',
        percentage: 100
      },
      {
        id: 4,
        content:
          'ESLint 对应编码规范，Git Hooks 对应 Git 规范。<br /> 想要开发出大厂标准的企业级项目，需要先从规范做起！',
        title: 'ESLint + Git Hooks',
        percentage: 100
      },
      {
        id: 5,
        content:
          '阿里前端 P7 岗被称为 《技术专家》，也有人喜欢叫他们为 “前端架构师”，既然被称为 “架构师” ，那么架构设计当然是不可缺少的一环咯',
        title: '架构设计',
        percentage: 100
      },
      {
        id: 6,
        content:
          '全面的后台权限验证系统，实现了 <b>页面权限、功能权限、动态权限、权限配置</b> 等全方位的权限功能',
        title: '权限验证（页面权限、功能权限、动态权限、权限配置）',
        percentage: 100
      },
      {
        id: 7,
        content: '对用户的功能引导',
        title: '功能引导',
        percentage: 100
      },
      {
        id: 8,
        content: '根据路由动态生成的 Menu 菜单，实现真正的 <b>配置 Menu</b>',
        title: '可配置 + 收缩侧边栏',
        percentage: 100
      },
      {
        id: 9,
        content: '动态生成的面包屑数据',
        title: '动态面包屑',
        percentage: 100
      },
      {
        id: 10,
        content: '便签快捷导航功能',
        title: 'Tags View',
        percentage: 100
      },
      {
        id: 11,
        content: '自定义的 svg Icon 配合 el Icon 自动分配导入',
        title: 'svg sprite 图标',
        percentage: 100
      },
      {
        id: 12,
        content: '多语言的国际化功能实现',
        title: '国际化',
        percentage: 100
      },
      {
        id: 13,
        content: '主题更换功能，提供缓存实现',
        title: '动态换肤',
        percentage: 100
      },
      {
        id: 14,
        content: '根据路由配置自动化生成的页面搜索数据，无需手动配置',
        title: '页面搜索',
        percentage: 100
      },
      {
        id: 15,
        content: 'excel 表格的导入、导出实现',
        title: 'excel 导出、导入',
        percentage: 100
      },
      {
        id: 16,
        content: '页面数据导出为 zip',
        title: 'zip 导入',
        percentage: 100
      },
      {
        id: 17,
        content: '常用的编辑器功能，包含 富文本编辑器 && MarkDown 编辑器',
        title: '富文本 + MarkDown 编辑器',
        percentage: 100
      },
      {
        id: 18,
        content:
          '表格列表的常见操作，多用于包含表格项的展示功能中。包括：动态表格 && 拖拽表格 && 内联编辑表格 ',
        title: '动态表格 + 拖拽表格 + 内联编辑表格',
        percentage: 100
      },
      {
        id: 19,
        content:
          '页面级的错误处理由 vue-router 统一处理。包含 401 和 404 的错误处理',
        title: '统一错误处理',
        percentage: 100
      },
      {
        id: 20,
        content: '构建与发布',
        title: '发布',
        percentage: 100
      },
      {
        id: 21,
        content:
          '除了以上功能之外，我们还实现了很多其他的功能，比如：CDN、动态的环境变量配置、懒加载、跨域等等',
        title: '其他',
        percentage: 100
      }
    ]
  }
}

const chapters = {
  en: {
    data: [
      {
        id: 1,
        timestamp: 'Chapter One',
        content: 'Course Guide'
      },
      {
        id: 2,
        timestamp: 'Chapter Two',
        content:
          'ESLint + Git Hooks, a standardized programming specification solution for major manufacturers'
      },
      {
        id: 3,
        timestamp: 'Chapter Three',
        content: 'Project architecture solution to build a login infrastructure'
      },
      {
        id: 4,
        timestamp: 'Chapter Four',
        content: 'Project architecture solution to build Layout infrastructure'
      },
      {
        id: 5,
        timestamp: 'Chapter Five',
        content:
          'General function development of front-end integrated solutions for back-end projects'
      },
      {
        id: 6,
        timestamp: 'Chapter Six',
        content:
          'Personal center page of vue3 + element plus comprehensive implementation solution'
      },
      {
        id: 7,
        timestamp: 'Chapter Seven',
        content:
          'Implementation of user management page of excel, zip and front-end combined solution'
      },
      {
        id: 8,
        timestamp: 'Chapter Eight',
        content:
          'The role and permission page rendering of the permission control solution realizes the permission control function of the project'
      },
      {
        id: 9,
        timestamp: 'Chapter Nine',
        content: 'List sorting solution to achieve popular article ranking'
      },
      {
        id: 10,
        timestamp: 'Chapter Ten',
        content:
          'Article editing solution to realize the function of creating articles'
      },
      {
        id: 11,
        timestamp: 'Chapter Eleven',
        content:
          'Unified handling of error pages in the comprehensive error handling solution'
      },
      {
        id: 12,
        timestamp: 'Chapter Twelve',
        content: 'Construction and release of project release solutions'
      },
      {
        id: 13,
        timestamp: 'Chapter Thirteen',
        content: 'Course summary'
      }
    ]
  },
  zh: {
    data: [
      {
        id: 1,
        timestamp: '第一章',
        content: '课程导读'
      },
      {
        id: 2,
        timestamp: '第二章',
        content: '标准化大厂编程规范解决方案之ESLint + Git Hooks '
      },
      {
        id: 3,
        timestamp: '第三章',
        content: '项目架构解决方案之搭建登录基础架构'
      },
      {
        id: 4,
        timestamp: '第四章',
        content: '项目架构解决方案之搭建Layout基础架构'
      },
      {
        id: 5,
        timestamp: '第五章',
        content: '后台项目前端综合解决方案之 通用功能开发'
      },
      {
        id: 6,
        timestamp: '第六章',
        content: 'vue3 + element plus 综合实现解决方案之个人中心页面'
      },
      {
        id: 7,
        timestamp: '第七章',
        content: 'excel 、zip 与前端结合解决方案之用户管理页面实现'
      },
      {
        id: 8,
        timestamp: '第八章',
        content: '权限控制解决方案之角色、权限页面渲染实现项目的权限控制功能'
      },
      {
        id: 9,
        timestamp: '第九章',
        content: '列表排序解决方案之实现热门文章排名'
      },
      {
        id: 10,
        timestamp: '第十章',
        content: '文章编辑解决方案之实现创建文章功能'
      },
      {
        id: 11,
        timestamp: '第十一章',
        content: '错误综合处理方案之错误页面的统一处理'
      },
      {
        id: 12,
        timestamp: '第十二章',
        content: '项目发布解决方案之构建与发布'
      },
      {
        id: 13,
        timestamp: '第十三章',
        content: '课程总结'
      }
    ]
  }
}

export default [
  // feature
  {
    url: '/user/feature',
    type: 'get',
    response: (config) => {
      const lang = getQueryString(config.query, 'lang')
      return {
        code: 200,
        success: true,
        data: features[lang].data
      }
    }
  },
  // chapter
  {
    url: '/user/chapter',
    type: 'get',
    response: (config) => {
      const lang = getQueryString(config.query, 'lang')
      return {
        code: 200,
        success: true,
        data: chapters[lang].data
      }
    }
  }
]
